create table if not exists roles (
    id int8 generated by default as identity,
    creation_date timestamp,
    updated_date timestamp,
    role_name varchar(255),
    primary key (id)
);
create table if not exists tasks (
    id int8 generated by default as identity,
    creation_date timestamp,
    updated_date timestamp,
    description varchar(255),
    status varchar(255),
    title varchar(255),
    user_id int8,
    primary key (id)
);
create table if not exists user_role (
    user_id int8 not null,
    role_id int8 not null
);
create table if not exists users (
    id int8 generated by default as identity,
    creation_date timestamp,
    updated_date timestamp,
    email varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id)
);




alter table if exists roles add constraint UK_716hgxp60ym1lifrdgp67xt5k unique (role_name);
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists tasks add constraint FK6s1ob9k4ihi75xbxe2w0ylsdh foreign key (user_id) references users;
alter table if exists user_role add constraint FKt7e7djp752sqn6w22i6ocqy6q foreign key (role_id) references roles;
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;
